---
title: "DATA 110 Lab I"
author: "PKiambo"
date: "July 11,2019"
output: html_document
---
## Part 1

```{r}
## Read Data
library(ggplot2)
nba <- read.csv("http://datasets.flowingdata.com/ppg2008.csv",sep = ",")
```

```{r}
## Sort Data
nba <- nba[order(nba$PTS),]
```

```{r}
## Set row number to Names of Players
row.names(nba) <- nba$Name

#remove 1st column
nba <- nba [,2:20]
```

```{r}
## Convert from DataFrame to Matrix
nba_matrix <- data.matrix(nba)
```

```{r}
## Create a heatmap
nba_heatmap <- heatmap(nba_matrix, Rowv = NA, Colv = NA, col = cm.colors(256),scale = "column", margins = c(5,10))
```

```{r}
## Color Selection
nba_heatmap <- heatmap(nba_matrix, Rowv = NA, Colv = NA, col = heat.colors(256),scale = "column", margins = c(5,10))
```

```{r}
## Clean it up.

```

## Part 2

```{r}
## Read Data
data <- read.csv("http://datasets.flowingdata.com/post-data.txt",sep = ",")
```

```{r}
## Load the portfolio package
#install.packages("portfolio")
library(portfolio)
```

```{r}
## Make the Treemap
map.market(id=data$id, area=data$views, group=data$category, color=data$comments, main="FlowingData Maps")
```

```{r}
## Customize

```

